version: '2'
services:
  redis-node-0:
    image: fenglyu/redis-cluster:7.0
    volumes:
      - redis-cluster_data-0:/data
    environment:
      - 'REDIS_PASSWORD=fenglyu'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-1:
    image: fenglyu/redis-cluster:7.0
    volumes:
      - redis-cluster_data-1:/data
    environment:
      - 'REDIS_PASSWORD=fenglyu'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-2:
    image: fenglyu/redis-cluster:7.0
    volumes:
      - redis-cluster_data-2:/data
    environment:
      - 'REDIS_PASSWORD=fenglyu'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-3:
    image: fenglyu/redis-cluster:7.0
    volumes:
      - redis-cluster_data-3:/data
    environment:
      - 'REDIS_PASSWORD=fenglyu'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-4:
    image: fenglyu/redis-cluster:7.0
    volumes:
      - redis-cluster_data-4:/data
    environment:
      - 'REDIS_PASSWORD=fenglyu'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'

  redis-node-5:
    image: fenglyu/redis-cluster:7.0
    volumes:
      - redis-cluster_data-5:/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
    environment:
      - 'REDIS_PASSWORD=fenglyu'
      - 'REDISCLI_AUTH=fenglyu'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5'
      - 'REDIS_CLUSTER_CREATOR=yes'

volumes:
  redis-cluster_data-0:
    driver: local
  redis-cluster_data-1:
    driver: local
  redis-cluster_data-2:
    driver: local
  redis-cluster_data-3:
    driver: local
  redis-cluster_data-4:
    driver: local
  redis-cluster_data-5:
    driver: local
